### ISSUE TITLE
Hello. how are you?

### ISSUE THREAD

**Issue by cupid-gracer** [anhydrous99/cb_websock#1]
I am going to try to compile your source code, by the way, I can't compile it on ubuntu successfully.
Could you help me?
I need your help really.

<pre>/usr/bin/ld: CMakeFiles/cb_websock.dir/src/Websock.cpp.o: undefined reference to symbol &apos;CONF_modules_unload@@OPENSSL_1_1_0&apos;
/usr/bin/ld: /lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cb_websock.dir/build.make:100: cb_websock] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/cb_websock.dir/all] Error 2</pre>

Thank you.

**Comment by cupid-gracer** [comment]
I hope your help urgently.

**Comment by happydeveloper-hobby** [comment]
Hello Armando, I am desktop developer, too.
I also tried to run your code but the result is same like above.
I would like to know the reason.
Thank you.
PS:  I hope to keep in touch to develop with you if you are ok.

**Comment by anhydrous99** [comment]
CMake didn't correctly link OpenSSL, the commit I just pushed should have fixed it. Sorry for not seeing this earlier.
